### ISSUE TITLE
commit_author_email is_invalid

### ISSUE THREAD

**Issue by marrek13** [OpsLevel/report-deploy-github-action#3]
Hello,
Today we received an error during creating a new deployment:

Error: status 400; {"errors":[{"status":400,"title":"Error creating deploy","detail":{"commit_author_email":["is invalid"]}}]}

Could you please check and assist with why it is happening? Can it be related that the last commit in the repository is the DependaBot commit?

**Comment by rocktavious** [comment]
Hey @marrek13 - If you are having a problem please reachout to your company's OpsLevel customer success representative and they will get it put through the right process for you so it gets tracked.  We do not handle support through the opensource repo's issues.
